### ISSUE TITLE
Backup and restore

### ISSUE THREAD

**Issue by pwkooistra** [TronWatch/Desktop-Wallet#51] opened 2018-06-26 21:28 UTC
Restoring a fresh made wallet in the desktop app results in 2 different private keys

restoring the wallet with the words given at the backup screen gives other pk and receive address 
then given pk at the backup wallet screen.

Also when restoring the wallet from the first pk loses the restore words.

**Comment by metjm** [comment] 2018-06-26 22:15
hello @pwkooistra thanks for the report.
I just confirmed the issue, it was caused by the import being off by one, which meant it only used the first 23 words. I've pushed a fix here: https://github.com/TronWatch/Desktop-Wallet/commit/a8f5eabdca874a1b71f70a8f3fce38deb1ddcbfb 
we're pushing fixed binaries in a bit, i'll close this once those are out.

**Comment by metjm** [comment] 2018-06-27 03:07
hello @pwkooistra we have uploaded beta version 1.0.6.1 here https://github.com/TronWatch/Desktop-Wallet/releases/tag/beta-v1.0.6 which fixes the import issue.

**Closed by metjm** 2018-06-27 03:07 UTC
Labels: bug
