### ISSUE TITLE
Takes 2 and abit days to unfreeze tokens

### ISSUE THREAD

**Issue by PaoraBoo** [TronWatch/Desktop-Wallet#121] opened 2018-09-22 01:47 UTC
There are issues with this wallet freezing up and not allowing to process. 
1/ Tron Power **expiry date: 9/19/2018**. Kept getting error message to check expiry date on the 20th and 21st when to trying to unfreeze. On the 22nd the tokens appeared unfreezed in the wallet - so it takes 2 and a bit days to unfreeze my coins? Is this what is going to continue to happen? 
2/ After taking 2 and a bit days to unfreeze tokens, now cannot freeze tokens to select voting. Is this going to take 2 and a bit days also?
3/ Feedback - why is this feature available when it does not submit

**Comment by metjm** [comment] 2018-09-22 01:50
Hello, these updates were caused by the tron node 3.1.1 activation which broke compatibility and we had to reset our database. We're still syncing, which means that the transaction list and vote details are delayed.  Everything will be back to normal once the database is up to date. Sorry for the inconvenience. I'll close this issue because we have another one open for that: https://github.com/TronWatch/Desktop-Wallet/issues/113

**Closed by metjm** 2018-09-22 01:50 UTC
