### ISSUE TITLE
Back Again... another issue with Tronwatch

### ISSUE THREAD

**Issue by Rwoods227** [TronWatch/Desktop-Wallet#122] opened 2018-09-22 02:40 UTC
Previously I couldn't get my balances to show up (around two months ago) since then it worked on and off... late August I began freezing my TRX.... and now I am stuck with perm TP and can't unfreeze or send any TRX whatsoever; attempting to do so provides me with a extremely detailed "Unfreezing failed. Has it been 3 days? 'Tados Check Error" message. I can honestly say at this point it has been about 2 weeks not just 3 days.  

TVRivzUsNkgMu9K6CUUPPjrcUsuXzesabW

![image](https://user-images.githubusercontent.com/41523740/45912447-51ae2200-bdef-11e8-913c-4f95883efff9.png)

![image](https://user-images.githubusercontent.com/41523740/45912439-2aefeb80-bdef-11e8-9805-fbe3a3d1ee3b.png)

**Comment by metjm** [comment] 2018-09-22 02:42
Hello, these updates were caused by the tron node 3.1.1 activation which broke compatibility and we had to reset our database. 

The new nodes only accept new protobufs, so you need to download the latest version. https://github.com/TronWatch/Desktop-Wallet/releases/

We're still syncing, which means that the transaction list and vote details are delayed. Everything will be back to normal once the database is up to date. Sorry for the inconvenience. 

I'll close this issue because we have another one open for that: #113

**Closed by metjm** 2018-09-22 02:42 UTC
