### ISSUE TITLE
Voting Does Not Work / Unfreezing Tron has a bug / need to reset wallet to see most changes

### ISSUE THREAD

**Issue by cryptokeeper802** [TronWatch/Desktop-Wallet#119] opened 2018-09-21 14:59 UTC
A slew of problems going on right now with the wallet that I have identified.

With the new update the old transaction history is no longer showing.

When you send Tron, in order to see your balance reflect that it was sent, you must turn the wallet off and back on.

Even after sending that Tron it did not make a record in the transaction history.

However the Tron was successfully received at the address I sent to.

When you freeze Tron, you won't see the Tron Power show up until you turn the wallet off and then back on.

Same issue for if you want to unfreeze Tron.... however, if you select any specific amount of Tron to unfreeze... ALL of it unfreezes instead of the amount specified.  And of course to see that it worked and have the Tron back in your balance, you have to turn the wallet off and then back on.

And then of course, the voting is not working at all now.  Go to vote and submit, it says success, however votes are not allocated.  Even if you turn the wallet off and then back on, the votes never take.  

Hope this helps and we can see a more robust tronwatch wallet soon.

**Comment by Kondax** [comment] 2018-09-21 15:14
Duplicate of #113.

The node is currently synchronising with our database. Transactions are going through.

**Closed by Kondax** 2018-09-21 15:14 UTC

**Comment by cryptokeeper802** [comment] 2018-09-21 15:18
Yes the transactions are going through, but the voting process is not working.  Voting transactions are not working.

________________________________

**Comment by Magalon** [comment] 2018-09-21 15:19
Can you please give us your PUBLIC address so we can check this out?

**Comment by cryptokeeper802** [comment] 2018-09-21 15:37
TB2FZVfyhHJBk2ZR2iUN1QBY9PcymruPc3

**Comment by Kondax** [comment] 2018-09-21 16:19
That wallet only has 0.003 TRX in it.
